CREATE TABLE despesa
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo              VARCHAR(255),
    status            VARCHAR(255),
    metodo_pagamento  VARCHAR(255),
    responsavel       VARCHAR(255),
    descricao         VARCHAR(255),
    valor             DECIMAL,
    data              date,
    posicao           INTEGER                                 NOT NULL,
    horario_cadastro  TIMESTAMP WITHOUT TIME ZONE,
    horario_alteracao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_despesa PRIMARY KEY (id)
);

CREATE TABLE receita
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo              VARCHAR(255),
    status            VARCHAR(255),
    metodo_pagamento  VARCHAR(255),
    responsavel       VARCHAR(255),
    descricao         VARCHAR(255),
    valor             DECIMAL,
    data              date,
    posicao           INTEGER                                 NOT NULL,
    horario_cadastro  TIMESTAMP WITHOUT TIME ZONE,
    horario_alteracao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_receita PRIMARY KEY (id)
);
